### ISSUE TITLE
Save Outfit To File

### ISSUE THREAD

**Issue by Denyss600** [itsjustcurtis/MenyooSP#104]
[FiveM]
I'm trying to save my mp_f_freemode_01 ped with facial features but it doesn't save at all. The ShapeAndSkinTone it does save but the FacialFeatures and Overlays colours doesn't. Is possible to be fixed and save those values to XML file?

**Comment by itsjustcurtis** [comment]
I'm sure this is a duplicate of another issue, but I cannot for the life of me find it. I'll leave this open unless I find it again.

**Comment by vbelevcev** [comment]
> I'm sure this is a duplicate of another issue, but I cannot for the life of me find it. I'll leave this open unless I find it again.

Are you sure you tried to look? I gave you all the information on facial features, and ideas of what can be done, you pretended you didn't know what I was talking about and closed the topic.

**Comment by itsjustcurtis** [comment]
Ahh yes, thats where I had seen it.  Duplicate of #53

Closing this issue and reopening the original as there is much more history 

@SkyK0T if you can help me out with the details on discord I would very much appreciate it.

**Comment by vbelevcev** [comment]
> [Пять дней] Я пытаюсь сохранить свой mp_f_freemode_01 ped с чертами лица, но это не сохраняется вообще. Форму и оттенок он сохраняет, но цвета FacialFeatures и Overlays - нет. Можно ли исправить и сохранить эти значения в XML-файл?



> [FiveM] I'm trying to save my mp_f_freemode_01 ped with facial features but it doesn't save at all. The ShapeAndSkinTone it does save but the FacialFeatures and Overlays colours doesn't. Is possible to be fixed and save those values to XML file?

the problem is that the menu does not see the facial feature of the network player, and sees if created in the menu itself, the editor does not work correctly, it sees it as a passerby (Static_241 = PLAYER_PED_ID() as a network player 240, and the author is afraid of the courts rockstar )) and nothing to do with online does not want to do))) joke, I think you need to dig into the nativas, I already offered help, I was not understood, or did not want to understand now I'm just an observer, I do not know how to do it, but it's my long-time dream to save faces, I'm quietly doing my own version, for example, I sorted passersby by add-ons, and I did it at the beginning of the year, and not like you fixed a player a week ago) let's do it this way, you try to fix the face, and I'll give you my work with fixes and stuff, but in general I don't really see you fixing/adding features, you're doing nonsense like logs that are needed by developers and not by users.

**Comment by vbelevcev** [comment]
https://github.com/Jerrrry123/JerryScript
this is the creator of the lua script for the stand, has already realized something similar.
https://github.com/Jerrrry123/JerryScript/blob/main/JerryScript.lua
starting on line 1636
