### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by asd012345** [itsjustcurtis/MenyooSP#73]
When will the Chinese translation function be added to the Chinese display menu that is already supported in the China service area game

**Comment by TayMcKenzieNZ** [comment]
The languages provided by the game, and Menyoo are different and seperate. Menyoo is a third party application. You would have to provide the translations for Curtis to implement. I believe there's a file you can use to translate

**Comment by itsjustcurtis** [comment]
What Tay said, Any translations that exist are through the global language files in game. If a translation doesn't exist its because there is not an associated global value within the game that suits. I will not be making custom translations for specific languages, only adding global values where I see them as appropriate.

**Comment by itsjustcurtis** [comment]
duplicate of #38
