### ISSUE TITLE
Teleportation problem with manage marker!

### ISSUE THREAD

**Issue by Gidoxx** [itsjustcurtis/MenyooSP#96]
Teleportation works! But when you get into a vehicle and get out, the teleportation no longer works! Before it worked fine! I tested this with my rooftop map as well as other maps!

**Comment by itsjustcurtis** [comment]
I seem to recall this being an issue on the original MAFINS repo, but we really struggled to figure out what the cause was. Leaving this as an open bug but I doubt it will be fixed any time soon

**Comment by mistahwolf** [comment]
> I seem to recall this being an issue on the original MAFINS repo, but we really struggled to figure out what the cause was. Leaving this as an open bug but I doubt it will be fixed any time soon

Yep and still is since no one over there has responded. So, I figured out a 'fix' but the bug will need to be resolved. 'Yes' for whatever reason, the code changes on your ped when getting into a vehicle or riding a motorcycle/boat/plane. To access the marker teleports, 'save' your ped's current skin and 'reapply' it after exiting the vehicle. However, you can still go through the teleports in a vehicle long as 'allow vehicle access' is checked in the marker settings. Hope this helps until a fix is made.

**Comment by Gidoxx** [comment]
> > I seem to recall this being an issue on the original MAFINS repo, but we really struggled to figure out what the cause was. Leaving this as an open bug but I doubt it will be fixed any time soon
> 
> Yep and still is since no one over there has responded. So, I figured out a 'fix' but the bug will need to be resolved. 'Yes' for whatever reason, the code changes on your ped when getting into a vehicle or riding a motorcycle/boat/plane. To access the marker teleports, 'save' your ped's current skin and 'reapply' it after exiting the vehicle. However, you can still go through the teleports in a vehicle long as 'allow vehicle access' is checked in the marker settings. Hope this helps until a fix is made.

hi indeed! it doesn't solve the problem but it's a good solution to troubleshoot! thanks for your answer! I'll tell the user to do like that in the meantime
